### ISSUE TITLE
Error related to class import

### ISSUE THREAD

**Issue by ma4ypic4y** [isaaccorley/ChesapeakeRSC#2]
notebooks/make_example_figures.ipynb

``` python
from src.datasets import ChesapeakeRSC
import matplotlib.pyplot as plt
import numpy as np
```

But the class itself in src.datasets is called **ChesapeakRSC**.

**Comment by isaaccorley** [comment]
Thanks for catching. I think this was me incorrectly renaming the dataset everywhere. Give me a few to fix

**Comment by isaaccorley** [comment]
@ma4ypic4y I believe I've fixed the issue but let me know if you run into problems.
